# Build and Push Hugo site to gh-pages
name: build-push

# trigger events
on:
  workflow_dispatch:
    
  push:
    branches:
      - 'main'
    paths:
      - "src/**/*"
    

jobs:
  
  # Build & Push hugo site
  hugo:
    name: build-push
    if: ${{ github.repository == 'sujaykumarh/notebook' }}

    runs-on: ubuntu-latest
    steps:

      # Pull Source Code
      - name: ‚úÖ Checkout Source
        uses: actions/checkout@v2

      - name: ‚¨áÔ∏è pull git submodules
        run: git submodule update --init --recursive

      - name: üî® Build Hugo Site
        run: |
          cp .env.example .env
          sh build.sh

      - name: ‚ÑπÔ∏è Setup files in dist
        run: |
          cp README.md src/dist/dist-readme.md
          touch src/dist/.nojekyll
          if [ -f "CNAME" ]; then cp CNAME src/dist/CNAME; fi

      - name: üöÄ Push to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: src/dist
          MESSAGE: "üî® Build gh-pages from {target-branch} {sha}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}